### PR TITLE
Add initial implementation of different border radius

### LINKED ISSUE #26: Support different border radii
Currently we only support one border radius. To support different radii we'd have to make our own view with different radii because there's not SwiftUI version

### PR DESCRIPTION
**Pull request by kerrmarin**
Adds support for different radiuses per corner

Fixes #26

### CODE REVIEW

**Review by deanWombourne — COMMENTED** [review]
If all the corners have the same corner radius, is it more efficient to use a RoundedRectangle, and fall back to a clip path only if they are different? (Making the assumption that SwiftUI's RoundedRectangle is optimized?)

**Comment by kerrmarin** [comment]
@deanWombourne yeah, why not. Let Apple do the heavy lifting 👍

**Comment by kerrmarin** [comment]
@deanWombourne @atomoil ping

**Comment by kerrmarin** [comment]
@deanWombourne @atomoil ping

**Review by deanWombourne — APPROVED** [review]
LGTM

**Pull request merged**
