### PR TITLE
Install dependencies 

### LINKED ISSUE #4: Error when a font is in a font collection
When trying to extract a sketchfile to SwiftUI, if the Sketch file has a font that is in a font collection an error is shown:

```
ERROR: Avenir Next Regular is in a font collection (/System/Library/Fonts/Avenir Next.ttc), but could not be extracted
  (Note, you need to install fonttools - 'brew install fonttools' should do it)
```

If `fonttools` is a requirement of this library it should either be installed as part of the installation of it (if possible) or set as a requirement in the README

### PR DESCRIPTION
**Pull request by kerrmarin**
Install both brew and fonttools if you don't have them when you install. What do you think @atomoil  @deanWombourne ? Fixes #4

### CODE REVIEW

**Comment by atomoil** [comment]
Nice work! But...

Isn't the dependency in `sketch-to-svg` if so any fix should go there.

Homebrew is only for mac, so this wouldn't work on a non-mac system and font tools isn't mac specific, so that's one downside to auto installing homebrew.

I feel a bit iffy about installing homebrew as part of an npm package, if people don't know it's installed and there's a (major) security issue with homebrew then they're unlikely to know to update it leaving them vulnerable.  So that's a second downside to auto installing homebrew

I feel ok with installing fonttools if they already have homebrew installed. Although ideally the installer would prompt them to install font tools (not even sure that's possible or desirable tho')

Also the script should fail gracefully if font tools is not installed (which is a separate issue)

**Comment by kerrmarin** [comment]
yeh, fair i wasn't sure about this myself anyway!

**Comment by atomoil** [comment]
I think a tweaked version would be great in the `sketch-to-svg` library

**Comment by kerrmarin** [comment]
Yeah makes sense, I'll look into that

**Pull request closed without merging**
